### ISSUE TITLE
Print option not fonctionnal

### ISSUE THREAD

**Issue by Xalava** [ThibaultFriedrich/value-proposition-canvas#1]
When pushing print, I just get a new tab open
Chrome / Ubuntu 16.10

**Comment by friedrith** [comment]
Thanks for your feedback. Can you describe me the current behavior ? In theory, it opens a new tab with the printer activated in front as on this screenshot. It is the case for you ?

 
![image](https://cloud.githubusercontent.com/assets/4005226/21138484/926e4ec4-c12e-11e6-8e34-1e74eb759da3.png)

**Comment by Xalava** [comment]
Thanks for the info
 - Right, the print dialog appears after ~ 3 seconds
 - Page setup is same as yours, 3 pages .. whatever the config is

**Comment by friedrith** [comment]
Ok. I have just seen this bug. It seems to happen with the last version of chrome. I am gonna to change it for a simple pdf export next week.

**Comment by friedrith** [comment]
Hi,

I have just made improvements on the application : it is now available on [http://canvas.techmind.io/](http://canvas.techmind.io/). The exportation should now be possible. Tell me if it is good for you.
